name: build_ErfanGSIs

on: 
  workflow_dispatch:
    inputs:
      ROM_URL:
        description: http://bigota.d.miui.com/V12.0.5.0.QFACNXM/miui_CEPHEUS_V12.0.5.0.QFACNXM_d14054540d_10.0.zip
        required: true
      ROM_TYPE:
        description: ab
        required: true
      RELEASE_NAME:
        description: MIUI
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq install git wget
       
       - name: Clone ErfanGSI Source Code
         run: | 
            git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git ErfanGSIs
         
       - name: Fix exit
         run: |
              sed -i 's/\|\| exit 1//g' ErfanGSIs/url2GSI.sh
              sed -i 's/exit 1//g' ErfanGSIs/url2GSI.sh
       
       - name: Setting up requirements
         run: |
              cd ErfanGSIs
              mkdir ./output
              sudo apt install python3-pip
              sudo bash ./setup.sh
       
       - name: Download Stock Rom
         run: |
              cd ErfanGSIs
              sudo bash ./url2GSI.sh -c --ab "${{ github.event.inputs.ROM_URL }}" "${{ github.event.inputs.ROM_TYPE }}"
              
       - name: Pack GSI
         run: |
           sudo apt install tar gzip
           tar -cvf ErfanGSIs/output/GSI.tar ErfanGSIs/output
           gzip -9 -c ErfanGSIs/output/GSI.tar > GSI.tar.gz
              
       - name: Upload GSI
         uses: ncipollo/release-action@v1.8.6
         with:
           artifacts: ErfanGSIs/output/*
           name: ErfanGSI
           tag: ErfanGSI
           token: ${{ secrets.GITHUB_TOKEN }}
